name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    # Inyectar variables falsas directo al SO para que Jest no falle
    env:
      MI_SMTP_HOST: smtp.gmail.com
      MI_SMTP_PORT: 587
      MI_SMTP_USER: test@test.com
      MI_SMTP_PASS: test
      DB_URI: mongodb://localhost:27017/test
      JWT_SECRET: supersecret

    strategy:
      matrix:
        node-version: [lts/*]

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Build backend server
      run: |
           cd ./backend
           npm install
           npm run lint
           npm run build

    - name: Build admin panel
      run: |
           cd ./admin
           npm install --force
           npm run lint
           npm run build

    - name: Build frontend
      run: |
           cd ./frontend
           npm install --force
           npm run lint
           npm run build

    - name: Build mobile app
      run: |
           cd ./mobile
           npm install
           npm run lint
           npm run ts:check
