name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Build backend server
      env:
        MI_SMTP_HOST: smtp.gmail.com
        MI_SMTP_PORT: "587"
        MI_SMTP_USER: test
        MI_SMTP_PASS: test
        MI_SMTP_FROM: test@test.com
        DB_URI: mongodb://localhost:27017/test
        JWT_SECRET: supersecret
      run: |
        cd ./backend
        npm install
        npm run lint
        npm run build

    - name: Build admin panel
      run: |
        cd ./admin
        npm install --force
        npm run lint
        npm run build

    - name: Build frontend
      run: |
        cd ./frontend
        echo "VITE_NODE_ENV=production" > .env
        echo "VITE_MI_API_HOST=https://movinin-plus-knzp.onrender.com" >> .env
        echo "VITE_MI_CDN_USERS=https://movinin-plus-knzp.onrender.com/cdn/movinin/users" >> .env
        echo "VITE_MI_CDN_PROPERTIES=https://movinin-plus-knzp.onrender.com/cdn/movinin/properties" >> .env
        echo "VITE_MI_CDN_LOCATIONS=https://movinin-plus-knzp.onrender.com/cdn/movinin/locations" >> .env
        npm install --force
        npm run lint
        npm run build
        cp build/index.html build/404.html

    - name: Build mobile app
      run: |
        cd ./mobile
        npm install
        npm run lint
        npm run ts:check

    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./frontend/build
