name: containerize

permissions:
  contents: read
  packages: write

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      name:
        type: choice
        required: true
        description: environment for the container image
        options:
          - development
          - staging
          - production
        default: development

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        component: [frontend, backend, admin]

    env:
      REPO_PREFIX: ghcr.io/${{ github.repository }}/${{ github.event.inputs.name || 'development' }}/${{ matrix.component }}

    steps:
      - uses: actions/checkout@v4

      - name: create-env-files
        run: |
          cp ${{ matrix.component }}/.env.docker.example ${{ matrix.component }}/.env.docker

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: build-and-push-docker-image
        run: |
          REPO_PREFIX_LOWER=$(echo "$REPO_PREFIX" | tr '[:upper:]' '[:lower:]')

          docker build \
            -t $REPO_PREFIX_LOWER:${{ github.sha }} \
            -f ${{ matrix.component }}/Dockerfile .

          docker push $REPO_PREFIX_LOWER:${{ github.sha }}

          docker tag \
            $REPO_PREFIX_LOWER:${{ github.sha }} \
            $REPO_PREFIX_LOWER:latest

          docker push $REPO_PREFIX_LOWER:latest
